-- Execute this script in your Supabase SQL Editor

-- 1. Add fields to customers table
ALTER TABLE customers
ADD COLUMN IF NOT EXISTS cpf VARCHAR(20),
ADD COLUMN IF NOT EXISTS phone VARCHAR(20),
ADD COLUMN IF NOT EXISTS cep VARCHAR(10),
ADD COLUMN IF NOT EXISTS street VARCHAR(255),
ADD COLUMN IF NOT EXISTS number VARCHAR(20),
ADD COLUMN IF NOT EXISTS complement VARCHAR(255),
ADD COLUMN IF NOT EXISTS district VARCHAR(255),
ADD COLUMN IF NOT EXISTS city VARCHAR(255),
ADD COLUMN IF NOT EXISTS state VARCHAR(2);

-- 2. Add fields to orders table
ALTER TABLE orders
ADD COLUMN IF NOT EXISTS external_code VARCHAR(255),
ADD COLUMN IF NOT EXISTS transaction_token VARCHAR(255),
ADD COLUMN IF NOT EXISTS pix_copy_paste TEXT,
ADD COLUMN IF NOT EXISTS qr_code_url TEXT,
ADD COLUMN IF NOT EXISTS payload_enviado JSONB,
ADD COLUMN IF NOT EXISTS payload_recebido JSONB;
